config/routes.rb
Rails.application.routes.draw do

  root to: "events#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :index, :edit, :update] do
    resources :avatars, only: [:create]
  end

  resources :charges

  resources :events do
    resources :attendances
    resources :pictures, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  # after_create :confirmation_send

  # def confirmation_send
  #   AttendanceMailer.confirmation_email(user).deliver_now
  # end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
  belongs_to :admin, class_name: "User"
  has_one_attached :picture
  
  validates :start_date, 
    presence: true

    #impossible de créer ou modifier un événement dans le passé

  validates :duration, presence: true,
    numericality: { greater_than: 0}
    validate :is_a_multiple_of_5
    #doit être un multiple de 5, et est strictement positif

  validates :title,
    presence: true,
    length: { in: 5..140 }

  validates :description, 
    presence: true, 
    length: { in: 20..1000 }

  validates :price,
    presence: true,
    numericality: {greater_than: 0, less_than: 1001}
  
  validates :location, presence: true
  validates :picture, presence: true

  def is_a_multiple_of_5
    if (duration.to_i)%5 != 0
      errors.add(:duration, "La durée doit être un multiple de 5")
    end
  end

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "can't be in the past") if !start_date.blank? and start_date < Date.today
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: 'admin_id', class_name: 'Event', dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances
  
  has_one_attached :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :description, :avatar)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :description, :current_password, :avatar)}
  end  

  # def configure_devise_parameters
  #   devise_parameter_sanitizer.permit(:update) { |u| u.permit(:email, :password, :password_confirmation, :first_name, :last_name, :description)}
  # end  

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def new
    @user = current_user
    @event = Event.find(params[:event_id])
    @amount = @event.price
    @stripe_amount = (@amount * 100).to_i
  end

  def create
    # Amount in cents
    @user = current_user
    @event = Event.find(params[:event_id])
    @amount = @event.price
    @stripe_amount = (@amount * 100).to_i
    stripe_customer_id = @user.id
  
    begin
      customer = Stripe::Customer.create({email:params[:stripeEmail],source:params[:stripeToken],})
    
      charge = Stripe::Charge.create({customer:customer.id,amount:@stripe_amount,description: 'Paiement en cours',currency: 'eur',})
  
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_attendance_path
    end

    Attendance.create(user: current_user, event: @event, stripe_customer_id: customer.id) if charge.paid

  end 

  def index
    @attendances = []
      Attendance.all.each do |attendance|
        @attendances << attendance
      end
  end

  def show
    @event = Event.find(params[:event_id])
    @attendees = []
    @a = @event.users
    @a.each do |user|
      @attendees << user
    end
    
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end

  def update
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new

  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({email:params[:stripeEmail],source:params[:stripeToken],})
  
    charge = Stripe::Charge.create({customer:customer.id,amount:@amount,description: 'Rails Stripe customer',currency: 'eur',})
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :authenticate_user!, only: [:new, :create]
  
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new
    @event.start_date = params[:start_date]
    @event.duration = ((params[:duration].to_i) * 5)
    @event.title = params[:title]
    @event.description = params[:description]
    @event.price = params[:price]
    @event.location = params[:location]
    @event.picture = params[:picture]
    @event.admin = current_user

    if @event.save
      flash[:success] = "Evènement sauvegardé!"
      redirect_to(root_path)
    else
      render "new"
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
    @end_date = @event.start_date + @event.duration
  end

  def update
    @event = Event.find(params[:id])
    event_params = params.require(:event).permit(:title, :description, :start_date, :duration, :price, :location, :picture)
    if @event.update(event_params)
      flash[:success] = "Evènement mis à jour."
      redirect_to(@event)
    else
      render :edit
    end
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.picture.attach(params[:picture])
    redirect_to(event_path(@event))
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def index
    @events = Event.all
  end

  def secret
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @events=[]
      Event.all.each do |event|
        if event.admin.id == current_user.id.to_i
          @events << event
        end
      end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def is_current_user_attendee
    @attendees = []
    @event.attendances.each do |attendance|
      if attendance.user_id == current_user.id
        return true
      end
    end
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/_attendees.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">

    <script src="https://kit.fontawesome.com/baa801bcb8.js" crossorigin="anonymous"></script>


    <title>Cartes</title>
</head>
<body>


<h3>Cartes participants événements</h3>
<section class="container">
<%@attendees.each do |attendee| %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-6 mt-3">
        <div class="card">
          <div class="card-horizontal">
            <div class="img-square-wrapper">
              <img class="" src="http://via.placeholder.com/300x180" alt="Card image cap" height="100px" width="100px">
            </div>
            <div class="card-body">
              <%= attendee.first_name %> <%= attendee.last_name %>
              <p class="card-text"><%= attendee.description %></p>
              <p class="card-text"><small class="text-muted"><%= attendee.email %></small></p>
            </div>
          </div>
          <div class="card-footer align-items-center justify-content-center">
            <small><a href="#" class="text-muted text-right">voir profil</a></small>
          </div>
        </div>
      </div>    
    </div>
  </div>
<% end %>
</section>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/attendances/create.html.erb
<h1>Votre paiement est maintenant confirmé !</h1>

<h2>Merci <%= @current_user.first_name %> pour votre achat de <%= @amount %> € !</h2>

<h3>Un email vous a été envoyé à <%= @current_user.email %> avec le récapitulatif de votre commande. A bientôt sur notre site !</h3>

<%= link_to "Retour à la page de l'évènement", event_path(@event.id), class:"btn btn-warning" %>

app/views/attendances/new.html.erb
<h1>Bienvenue sur la page de paiement, <%= @current_user.first_name %></h1>

<p>Tu t'apprêtes à acheter un billet pour : <%= @event.title %></p>

<p>Ce billet te coutera <%= @event.price %> euros </p>

<%= form_tag event_attendances_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>

  <label class="amount">
  
    <span>Le prix total à payer sera de <%= @event.price %>€</span>
  </label>
</article>

<br/>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Paiement en cours pour ton billet"
    data-amount="<%= @stripe_amount %>"
    data-currency="eur"
    data-locale="auto">
</script>
<% end %>

app/views/attendances/show.html.erb
<body>

<h1>Voici les participants à l'évènement</h1>

<section class="container">
  

<%= render "attendees" %>

<br/>

<%= link_to "Modifier l'évènement", edit_event_path(@event.id), class:"btn btn-warning" %>
<%= link_to "Supprimer l'évènement", event_path(@event.id), data: {confirm: "Êtes-vous sûr de vouloir supprimer cet évènement ?"}, class:"btn btn-danger", method: "delete"%>
</section>
</body>

app/views/avatars/create.html.erb
<%if @user.avatar.attached?%>
<h3>Voici ton avatar actuel</h3>
  <%= image_tag @user.avatar, alt: 'avatar' %>
  <p> Tu peux le modifier via le formulaire ci-dessous. </p>
<%else%>
  <p>Tu n'as pas encore d'avatar ! Tu peux en ajouter un via la formulaire ci-dessous. </p>
<%end%>


<%= form_tag user_avatars_path(@user), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>

      <label class="amount">
        <span>Amount: $1000</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%=Rails.configuration.stripe[:publishable_key]%>"
            data-description="Acheter un billet pour l'évènement "
            data-amount="500"
            data-locale="auto"></script>
<% end %>
<% end %>

app/views/events/_citycard.html.erb
<section class="container">

    <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
        Paris
        <span class="badge bg-primary rounded-pill">14</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
        Lyon
        <span class="badge bg-primary rounded-pill">2</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
        Marseille
        <span class="badge bg-primary rounded-pill">1</span>
        </li>
    </ul>
</section>

app/views/events/_indexcard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">

    <script src="https://kit.fontawesome.com/baa801bcb8.js" crossorigin="anonymous"></script>


    <title>Cartes</title>
</head>
<body>

  <section class="container card-group">

<% @events.each do |event| %> 

    <div class="row row-cols-1 row-cols-md-2 g-4">
      <div class="col">
        <div class="card m-3 card-hover" style="width: 18rem;">
         <%if event.picture.attached?%>
            
            <%= image_tag(event.picture)%>
          <% else %>
            <%= image_tag("https://images-ext-1.discordapp.net/external/2dkSeg_r2Aj4f58DnU-LOfOLyIZfyMoTm9gYYNf_EUU/https/www.pkfoot.com/wp-content/uploads/2020/03/foot-anglais.jpg?width=1130&height=660")%>

          <% end %>
          <!-- Card Body -->
          <div class="card-body">
            <h4 class="mb-2 text-truncate-line-2 "><%= link_to event.title, event_path(event.id), class:"text-decoration-none"%></a></h4>
            <!-- List -->
            <ul class="my-3 list-inline">
              <li class="list-inline-item ">
                <i class="far fa-clock mr-1"></i><a> </a><%= event.duration %> minutes
              </li>
              <li class="list-inline-item">
                <i class="fas fa-euro-sign"></i><a> </a><%= event.price %>
              </li>
            </ul>
            <ul class="my-3 list-inline">
              <li class="list-inline-item">
                <i class="fas fa-map-marker-alt"><a> </a></i><%= event.location%>              
              </li>
              
            </ul>
            <div class="lh-1">
              <span>
                <i class="fas fa-user-friends"></i>
              </span>
              <span class="font-size-xs text-muted"><%= event.attendances.count %></span>
              <span class="text-warning text-muted">participants</span>
            </div>
          </div>
          <!-- Card Footer -->
          <div class="card-footer">
            <div class="row align-items-center no-gutters">
              <div class="col-auto">
                <img src="assets/images/avatar/avatar-4.jpg" class="rounded-circle avatar-xs" alt="">
              </div>
              <div class="col ml-2">
                <span>Créé par : <%= event.admin.first_name%></span>
              </div>
              <div class="col-auto">
                <a href="#!" class="text-muted bookmark">
                  <i class="fe fe-bookmark  "></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
<% end %>
    
  </section>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/events/_jumbotron.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="style.css">

    <title>Eventbrite</title>
</head>
<body>

  <section class="jumbotron py-5 py-lg-10 text-center bg-light d-flex flex-column justify-content-center" >
    <div class="container pb-5">
      <div class="row justify-content-center col-md-12 pb-5">
        <div class="col-xl-6 col-lg-7 col-md-8 col-sm-10 text-center pt-5">
        <h5 class="text-light fw-light pt-5">Bienvenue sur Eventbrite by THP </h5>
          <div class="pb-4"> 
          <h1 class="text-light font-weight-bold pt-3 fw-bold">Trouver et participer à des événements près de chez vous</h1>
            <div class="dropdown">
              <button class="btn dropdown-toggle text-primary font-weight-bold fs-1 border-none" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Paris
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Lyon</a>
                <a class="dropdown-item" href="#">Marseille</a>
                <a class="dropdown-item" href="#">Valencienne</a>
                <a class="dropdown-item" href="#">Strasbourg</a>
              </div>
            </div>
          </div>
          <%= link_to "Créer un évènement", new_event_path, class:"btn btn-primary" %>
          
        </div>
      </div>
    </div>
  </section>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/events/_newerror.html.erb
<% if @event.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer l'évènement' pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>  
  <% end %>

app/views/events/_show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="style.css">

    <script src="https://kit.fontawesome.com/baa801bcb8.js" crossorigin="anonymous"></script>

    <title><%= @event.title %></title>
</head>
<body style="height: 2000px;">
    <div class="bg-light row align-items-center" style="height: 500px;">
        <div class="container col-8" style="margin-top: -150px" >
            
                <h1 class="display-2 fw-bold text-primary "><%= @event.title %></h1>            
                <ul class="mt-3 list-inline fs-5">
                    <li class="list-inline-item ">
                        <i class="far fa-clock mr-1"></i><%= @event.duration %>
                    </li>
                    <li class="list-inline-item">
                        <i class="fas fa-euro-sign"></i><%= @event.price %> 
                    </li>
                    <li class="list-inline-item">
                        <span>
                            <i class="fas fa-user-friends"></i>
                        </span>
                        <span class="font-size-xs text-muted"><%= @event.attendances.count %></span>
                        <span class="text-warning text-muted">Participants</span>   
                    </li>
                </ul>
            
        </div>
    </div>
    <section class="container col-8 pb-5" style="margin-top: -150px;"> 
     
        <div class="row">
            <div class="col-8">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title text-muted py-3">Descritpion</h5>
                        <p class="card-text fs-5 pb-3"><%= @event.description %></p>
                        <ul class="list-group list-group-horizontal">
                            <li class="list-group-item"><i class="far fa-heart"></i></li>
                            <li class="list-group-item"><i class="fas fa-download"></i></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card" style="">
                    <%if @event.picture.attached?%>
                        <%= image_tag(@event.picture)%>
                    <% else %>
                     <img class="card-img-top" src="https://images.unsplash.com/photo-1485872299829-c673f5194813?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1982&q=80" alt="Card image cap">
                    <% end %>
                    <div class="card-body">
                        <ul class="mt-3 list-inline fs-5">
                            <li class="list-inline-item">
                                <i class="far fa-clock mr-1"></i><%= @event.duration %>
                            </li>
                            <li class="list-inline-item">
                                <i class="fas fa-euro-sign"></i><%= @event.price %> 
                            </li>
                            <li class="list-inline-item">
                                <span>
                                    <i class="fas fa-user-friends"></i>
                                </span>
                                <span class="font-size-xs text-muted"><%= @event.attendances.count %></span>
                                <span class="text-warning text-muted">Participants</span>   
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>  
    
        <div class="row py-3 align-items-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <ul class="list-group list-group-horizontal">
                            <img src="https://t4.ftcdn.net/jpg/02/15/84/43/240_F_215844325_ttX9YiIIyeaR7Ne6EaLLjMAmy4GvPC69.jpg" class="list-group-item" style="height: 42px; alt="">
                            <li class="list-group-item w-100"><%= @event.admin.first_name %></li>
                            <li class="list-group-item btn w-25">voir profil</li>

                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-4 h-100">
                <% if user_signed_in?  %>
                    <% if current_user == @event.admin %>
                    <div>
                        <%= link_to 'Mon espace évènement', event_attendance_path(@event), class:"btn btn-warning w-100 h-100 fs-3", event:params[:event] %>
                    </div>

                    <% elsif is_current_user_attendee == true %>
                        
                    <p>Tu participes déjà à cet événement, cliques ici pour voir d'autres événements suceptibles de te plaire:</p> 
                    <%= link_to 'Liste des évènements existants', root_path, class:"btn btn-warning w-100 h-100 fs-6"%>
                    
                    <% elsif %>
                        
                    <div>
                        <%= link_to 'Acheter un billet', new_event_attendance_path(@event), class:"btn btn-primary w-100 h-100 fs-3", event:params[:event] %>
                    </div>
                        
                    <% end %>

                <% else %>
                    <div>
                    <%= link_to 'Se connecter pour acheter un billet', new_user_session_path, class:"btn btn-warning w-100 h-100 fs-3", event:params[:event] %>
                    </div>
                <% end %>
            </div>
            
        </div>
        <div class="row py-3">
            <div class="col-12">
                <div class="card w-100">
                    <div class="card-body">
                        <ul class="list-group list-group-horizontal text-center">
                            <li class="list-group-item w-25"> <i class="fab fa-facebook"></i></li>
                            <li class="list-group-item w-25"><i class="fab fa-twitter"></i></li>
                            <li class="list-group-item w-25"><i class="fab fa-linkedin-in"></i></li>
                            <li class="list-group-item w-25"> <i class="fab fa-instagram"></i></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-4">
            </div>
        </div>    
   </section>

      <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/events/index.html.erb
<html>
  <body class= bg-light>

  <%= render "jumbotron" %>
  



  <div class="container pt-5 pb-4 fw-bold">
    <h3 class="fw-bold display-5"> Les prochains évènements </h3>
  </div>


    <%= render "indexcard" %>
    <%= render "citycard" %>

  </body>
    
</html>

app/views/events/new.html.erb
<%= render "newform" %>

app/views/events/show.html.erb
<html>

  <%= render "newerror" %>

  <body>


  <%= render "show" %>
  </body>
</html>

app/views/pictures/create.html.erb
<%if @event.picture.attached?%>
<h3>Voici la photo actuelle de l'évènement</h3>
  <%= image_tag @event.picture, alt: 'picture' %>
  <p> Tu peux la modifier via le formulaire ci-dessous. </p>
<%else%>
  <p>Tu n'as pas encore ajouter de photo pour ton évènement ! Tu peux en ajouter une via la formulaire ci-dessous. </p>
<%end%>


<%= form_tag event_pictures_path(@event), multipart: true do %>
  <%= file_field_tag :picture %>
  <%= submit_tag "mettre à jour" %>
<% end %>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>